In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])


arr1 = [[2,3,5],[3,4,5]]
arr2 = [[2,3,5],[3,4,5]]




print(arr)

['1' '2' '3' '4' '5' 'suman']


In [5]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [8]:
zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((3,2))
print(ones)

rand = np.random.rand(2,2)
print(rand)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.27943918 0.13036142]
 [0.03145335 0.51890458]]


In [9]:
# Array Attributes

a = np.array([[1,2,3],[4,5,6]])
print(a.ndim) #number of Dimension
print(a.shape) #rows and column
print(a.size) #total number of emelments
print(a.dtype)



2
(2, 3)
6
int64


Create a NumPy array from 1 to 20.

Reshape it into a 4×5 matrix.

Find the mean and sum of each row.

Extract only even numbers using slicing or condition.